-- [1] 기존 테이블 삭제
DROP TABLE TB_MEMBER CASCADE CONSTRAINT;
DROP TABLE TB_POST CASCADE CONSTRAINT;

-- [2] 회원 테이블
CREATE TABLE TB_MEMBER (
	USER_ID NUMBER PRIMARY KEY,                -- 회원 ID
	USERNAME VARCHAR2(100) NOT NULL,           -- 사용자명
	PASSWORD_HASH VARCHAR2(256) NOT NULL,      -- 비밀번호 해시
	JOIN_DATE DATE DEFAULT SYSDATE             -- 가입일
);

-- [3] 게시글 테이블
CREATE TABLE TB_POST (
	POST_ID NUMBER PRIMARY KEY,                -- 게시글 ID
	USER_ID NUMBER NOT NULL                    -- 작성자 (회원 ID)
		CONSTRAINT FK_POST_USER REFERENCES TB_MEMBER(USER_ID),
	TITLE VARCHAR2(200) NOT NULL,              -- 제목
	CONTENT VARCHAR2(4000) NOT NULL,           -- 내용
	MEMO_OPTION NUMBER DEFAULT 0 NOT NULL      -- 0:공개, 1:비공개, 2:체크메모
		CHECK (MEMO_OPTION IN (0, 1, 2)),
	MEMO_CHECK NUMBER DEFAULT 0,               -- 체크 상태
	TOPIC NUMBER DEFAULT 0 NOT NULL            -- 주제 코드 (0:공지, 1:개인, 2:업무)
		CHECK (TOPIC IN (0, 1, 2)),
	CREATED_AT DATE DEFAULT SYSDATE            -- 작성일
);

-- [4] 저장
COMMIT;

-- [5] 테스트 조회
SELECT * FROM TB_MEMBER;
SELECT * FROM TB_POST;


-- [1] 회원 데이터 삽입
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_NAME, MEMBER_PW)
VALUES (admin, 'admin', 'admin123');

INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_NAME, MEMBER_PW)
VALUES (2, 'bob', 'hash_pw_456');

-- [2] 게시글 데이터 삽입
INSERT INTO TB_POST (POST_NO, MEMBER_ID, POST_TITLE, POST_CONTENT, POST_OPTION, POST_CHECK, POST_TOPIC)
VALUES (177, '098', '첫 메모', '이건 공개 메모입니다.', 0, 0, 1);

INSERT INTO TB_POST (POST_ID, USER_ID, TITLE, CONTENT, MEMO_OPTION, MEMO_CHECK, TOPIC)
VALUES (102, 1, '비공개 메모', '비밀 메모입니다.', 1, 0, 1);

INSERT INTO TB_POST (POST_ID, USER_ID, TITLE, CONTENT, MEMO_OPTION, MEMO_CHECK, TOPIC)
VALUES (103, 2, '할 일 체크', '할 일을 완료했습니다.', 2, 1, 2);

-- [4] 저장
COMMIT;

-- [5] 테스트 조회
SELECT * FROM TB_MEMBER;
SELECT * FROM TB_POST;

DELETE FROM TB_MEMBER
WHERE MEMBER_ID ='123';